# Generated by Django 2.1.1 on 2019-03-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20180410_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(blank=True, default='1988-09-09', null=True),
        ),
    ]
